import { createConstants } from '../utils';

export default createConstants(
  'SAVE_RESUME',
  'MOVE_BLOCK',
  'MOVE_BULLET',
  'UPDATE_RESUME_WITH_SERVER_RESPONSE',
  'UPDATE_LOCAL_STATE',
  'UPDATE_LOCAL_STATE_HEADER',
  'UPDATE_LOCAL_STATE_FOOTER',
  'UPDATE_LOCAL_STATE_SAVEPRINT',
  'UPDATE_LOCAL_STATE_BLOCKS',
  'UPDATE_LOCAL_STATE_BULLETS'
  'SERVER_IS_SAVING_UPDATE',
  'CLIENT_IS_DIRTY_UPDATE'
);
