import { createConstants } from '../utils';

export default createConstants(
  'ADD_BLOCK',
  'ADD_BULLET',
  'CLIENT_IS_DIRTY_UPDATE',
  'HIDE_BLOCK',
  'HIDE_BULLET',
  'MOVE_BLOCK',
  'MOVE_BULLET',
  'POPULATE_DATA_FROM_LINKEDIN',
  'RESET_RESUME',
  'SAVE_RESUME',
  'SERVER_IS_SAVING_UPDATE',
  'UPDATE_LOCAL_STATE',
  'UPDATE_LOCAL_STATE_BLOCKS',
  'UPDATE_LOCAL_STATE_BULLETS',
  'UPDATE_LOCAL_STATE_FOOTER',
  'UPDATE_LOCAL_STATE_HEADER',
  'UPDATE_LOCAL_STATE_SAVEPRINT',
  'UPDATE_RESUME_WITH_SERVER_RESPONSE',
  'UPDATE_THESAURUS_RESULTS',
  'WORD_SEARCH'
);
